# Generated by Django 5.1.3 on 2025-06-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
